name: Deploy (dev)

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

  workflow_dispatch:

env:
  PROJECT_ID: k8s-react-gke
  GKE_CLUSTER: k8s-react-cluster
  GKE_ZONE: asia-east2-a
  IMAGE_NAME: docker-react
  
jobs:
  build:
    name: Deploy to GKE
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1
        
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y%m%d%H%M%S')"

      - name: Get registry path
        id: registry
        run: |
          echo "::set-output name=path::${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{ steps.date.outputs.date }}"
          echo "::set-output name=latest::${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:latest"

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ steps.registry.outputs.path }}
            ${{ steps.registry.outputs.latest }}

      - name: Setup gcloud auth
        uses: google-github-actions/setup-gcloud@v0.2.0
        with:
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          project_id: ${{ env.PROJECT_ID }}

      - name: Setup docker auth
        run: gcloud --quiet auth configure-docker

      - name: Setup k8s auth
        uses: google-github-actions/get-gke-credentials@v0.2.1
        with:
          cluster_name: ${{ env.GKE_CLUSTER }}
          location: ${{ env.GKE_ZONE }}
          credentials: ${{ secrets.GCP_SA_KEY }}
          project_id: ${{ env.PROJECT_ID }}

      - name: Update deployment image
        run: |
          kubectl apply -f k8s
          kubectl set image deployments/react-deployment react-web=${{ steps.registry.outputs.path }}

      - name: Deployed!
        run: echo App deployed to GKE
